# Generated by Django 4.0.6 on 2022-10-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('service', models.CharField(max_length=64)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
    ]
